-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "fullname_sender" TEXT NOT NULL,
    "cpf_sender" TEXT NOT NULL,
    "phone_sender" TEXT NOT NULL,
    "email_sender" TEXT NOT NULL,
    "address_sender" TEXT NOT NULL,
    "cep_sender" TEXT NOT NULL,
    "state_sender" TEXT NOT NULL,
    "uf_sender" TEXT NOT NULL,
    "city_sender" TEXT NOT NULL,
    "neighborhood_sender" TEXT NOT NULL,
    "street_sender" TEXT NOT NULL,
    "number_sender" TEXT NOT NULL,
    "complement_sender" TEXT NOT NULL,
    "fullname_receiver" TEXT NOT NULL,
    "cpf_receiver" TEXT NOT NULL,
    "phone_receiver" TEXT NOT NULL,
    "email_receiver" TEXT NOT NULL,
    "address_receiver" TEXT NOT NULL,
    "cep_receiver" TEXT NOT NULL,
    "state_receiver" TEXT NOT NULL,
    "uf_receiver" TEXT NOT NULL,
    "city_receiver" TEXT NOT NULL,
    "neighborhood_receiver" TEXT NOT NULL,
    "street_receiver" TEXT NOT NULL,
    "number_receiver" TEXT NOT NULL,
    "complement_receiver" TEXT NOT NULL,
    "weight" TEXT NOT NULL,
    "height" TEXT NOT NULL,
    "width" TEXT NOT NULL,
    "length" TEXT NOT NULL,
    "reverse" TEXT NOT NULL,
    "ar" TEXT NOT NULL,
    "own_hands" TEXT NOT NULL,
    "information" TEXT NOT NULL,
    "amount" TEXT NOT NULL,
    "quantity" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "tracking_code" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
